#!/usr/bin/env bash
set -e

testenv=../test-env
vm=$testenv/vm
pid=0

setUp() {
  $vm/make-vm
  . $vm/vm-env
  $vm/result/bin/run-nixos-vm &
  pid=$!

  # TODO poll until up
  sleep 10
}

tearDown() {
  kill $pid
}

testDummy() {
  # TODO do some work
  echo "Running test on $pid..."

  fail "test is incomplete"
}

. $testenv/shunit2/shunit2
