#!/usr/bin/env bash
set -e

nix-build '<nixpkgs/nixos>' -A vm -k -I nixos-config=./vm.nix

# To forward a port you can set export QEMU_NET_OPTS. In the following example port 2222 on the host is forwarded to port 22 in the vm:
export QEMU_NET_OPTS="hostfwd=tcp::2222-:22"
#export QEMU_OPTS="-nographic -serial mon:stdio" QEMU_KERNEL_PARAMS=console=ttyS0 
result/bin/run-nixos-vm

# Run
# result/bin/run-nixos-vm -display none
