#!/usr/bin/env bash
set -e

curl https://raw.githubusercontent.com/hbons/Dazzle/master/dazzle.sh --output dazzle
chmod +x dazzle


#dazzle setup

# Link a SparkleShare client
#dazzle link

# Create a new project
#dazzle create PROJECT_NAME